on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Test
        uses: ./
        id: test
        with:
          string: 'aasdfa/v1.0.1'
          pattern: '[\w\d/]*v(\d+(?:\.\d+)*)'
          replace-with: '$1'
      - name: Check equality
        run: '[[ "${{ steps.test.outputs.replaced }}" == "1.0.1" ]]'
  test-whitespace:
    runs-on: ubuntu-latest
    name: Test whitespaces
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Test
        uses: ./
        id: test
        with:
          string: '_replace_underscores_'
          pattern: '_'
          replace-with: ' '
          flags: 'g'
      - name: Check equality
        run: '[[ "${{ steps.test.outputs.replaced }}" == " replace underscores " ]]'